services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    volumes:
      - ./:/usr/bin/MiraiCore
    depends_on:
      - db
  db:
    image: mariadb:latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    privileged: true
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=TESTMODE
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    tty: true
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always
