services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    volumes:
      - ./:/usr/bin/MiraiCore
    depends_on:
      - db
  db:
    image: mariadb:latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    privileged: true
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=TESTMODE
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    tty: true
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always
  cron:
    build:
      context: ./cron
      dockerfile: cron.Dockerfile
    depends_on:
      - api
      - db
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cron:/opt/crontab/config.json
