services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    volumes:
      - ./:/usr/bin/MiraiCore
    depends_on:
      - db
  db:
    image: mariadb:latest
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    privileged: true
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=TESTMODE
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    tty: true
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always
  cron:
    build:
      context: .
      dockerfile: cron.Dockerfile
    depends_on:
      - api
      - db
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cron:/config.json/crontab/config.json
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiMTgxZmY2OThmODgxMWJjYTE4OWE0N2NkNTdiZjc0N2UiLCJ0IjoiM2MwNWJkZTYtNDcyNi00OWM0LWE1ZTgtM2Y3ZjUzOGMwZDQ0IiwicyI6Ik4yVmhZalV3WmpBdFpqTmpNaTAwTmpFNExXSTROalV0TjJFeVltTTROekUyTWpnMyJ9
    depends_on:
      - web
    restart: always